# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Books App Pipeline'
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Infra
    jobs:
    - job : InfraJob
      displayName : 'Create Infra' 
      steps:     
        - task: AzureCLI@3
          displayName: 'Create Az Resource Group'
          inputs:
            connectionType: 'azureRM'
            azureSubscription: 'Azure subscription 1(a81f821e-5466-4898-8671-bf41188f39b3)'
            scriptType: 'batch'
            scriptLocation: 'inlineScript'
            inlineScript: 'az group create -n az-rg -l uksouth'