# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Books App Pipeline'
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name : solution
    value : '**/*.sln'
  - name : buildPlatform
    value:  'Any CPU'
  - name : buildConfiguration
    value:  'Release'
  - group : BooksApp-variables

resources:
 repositories:
   - repository: reactRepo
     type: github
     name: Azure204-medium/Books-React
     #endpoint is the service connection name
     endpoint: Azure204-medium
   - repository: apiRepo
     type: github
     name: Azure204-medium/BooksApi
     endpoint: Azure204-medium
stages:
  - stage: Build
    displayName: 'Create Build'
    jobs:
      - job: BuildApp
        displayName: 'Build App'
        steps:
          - checkout: apiRepo
          - task: DotNetCoreCLI@2
            displayName: 'restore nuget packages'
            inputs:
              command: 'restore'
              projects: '$(solution)'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: 'Build .net'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: publish .net
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '**/Books.Api.csproj'
              arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish'
              zipAfterPublish: false

          - checkout: reactRepo

        
           # node install
          - task: UseNode@1
            displayName: 'Install node.js'
            inputs:
              version: '18.x'
          - script: node -v
            displayName: 'Check Node version'
          - script: dir
            displayName: 'Check folder structure'
          # React install
          - task: Npm@1
            displayName: 'Install npm'
            inputs:
              command: 'install'
              workingDir: '$(Build.SourcesDirectory)/Books-React'
            # React build
          - script: npm run build
            displayName: 'build react'
            workingDirectory: '$(Build.SourcesDirectory)/Books-React'
          - task: CopyFiles@2
            displayName: 'copy to wwwroot'
            inputs:
                SourceFolder: '$(Build.SourcesDirectory)/Books-React/build'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)/publish/SimpleBooksApi/wwwroot'

          - script: dir
            displayName: 'After copy Check folder structure'
          
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish/SimpleBooksApi'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/drop/app.zip'
              replaceExistingArchive: true
              verbose: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
              ArtifactName: 'drop'  
       
         
  - stage: Infra
    dependsOn: Build
    displayName: 'Az Infra'
    jobs:
      - job: InfraJob
        displayName: 'Create Az Infra Job'
        steps:
          - task: AzureCLI@3
            displayName: 'Create Az RG'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: 'Azure subscription 1(a81f821e-5466-4898-8671-bf41188f39b3)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'az group create -g $(booksResourceGroup) -l uksouth'

          - task: AzureCLI@3
            displayName: 'Create webapp and sql'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: 'Azure subscription 1(a81f821e-5466-4898-8671-bf41188f39b3)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group $(booksResourceGroup) --template-file $(Build.SourcesDirectory)/Iac/main.bicep --parameters $(Build.SourcesDirectory)/Iac/parameters/parameters.dev.json'

          - task: AzureCLI@3
            displayName: 'Update connection string'
            inputs:
              connectionType: 'azureRM'
              azureSubscription: 'Azure subscription 1(a81f821e-5466-4898-8671-bf41188f39b3)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'az webapp config connection-string set -n books-webapp-dev -g books-dev-rg  --connection-string-type SQLAzure --settings BooksDB="Server=tcp:books-sql-db-dev.database.windows.net,1433;Initial Catalog=books-sql-server-dev;Persist Security Info=False;User ID=sqlserveradmin;Password=Admin12345678!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

  - stage: deploy
    displayName: 'Deploy to Az'
    dependsOn: Infra
    jobs:
      - job: deployJob
        displayName: deploy to Az
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription 1(a81f821e-5466-4898-8671-bf41188f39b3)'
              appType: 'webApp'
              WebAppName: '$(booksWebApp)'
              package: '$(System.ArtifactsDirectory)/drop/*.zip'

         